# Generated by Django 4.2.4 on 2023-09-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rnd_key',
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.TextField(blank=True, null=True, verbose_name='страна'),
        ),
    ]
